format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$time\
$python\
$character"""

command_timeout = 2_000

[directory]
style = "blue"
truncate_to_repo = false

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
disabled = false  # this is slow (~1 second)
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
disabled = false
format = "[$duration]($style) "
style = "yellow"
show_notifications = true
min_time_to_notify = 10_000
min_time = 2_000

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[time]
disabled = true
format = "[$time]($style) "
style = "#9cc9b7"

