# https://starship.rs/config/#prompt

[package]
disabled = true

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[cmd_duration]
min_time = 2_000
style = "#f0f4b7"
show_notifications = true
min_time_to_notify = 10_000

[time]
disabled = false
format = "[$time]($style) "
style = "#9cc9b7"

[directory]
truncate_to_repo = false
style = "blue"
truncation_length = 10

[aws]
style = "bold #f0c9b7"

[kubernetes]
disabled = true
style = "#50c878 bold"

